# scene
scene: empty_table # empty, empty_table
build_graph: false
load_texture: true
pybullet_load_texture: true
trav_map_type: no_obj
trav_map_resolution: 0.1
trav_map_erosion: 3
# should_open_all_doors: true

# change this path according to the required table 
table_urdf_path: objects/table/9ad91992184e2b3e283b00891f680579/9ad91992184e2b3e283b00891f680579.urdf
visual_marker: sphere
# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# table top task specific parameters 
# min_change: 0.3
# max_change: 0.4
table_height: 0.63
table_scaling: 2 
intial_robot_pos: [0, 0, 0]
# robot
robot: Tiago_Single # Fetch, Tiago_Single
is_discrete: false
wheel_velocity: 0.8
torso_lift_velocity: 0.8
arm_velocity: 0.8

# task
task: reaching_random
target_dist_min: 1.0
target_dist_max: 100.0
goal_format: polar
task_obs_dim: 3
additional_states_dim: 3 
auxiliary_sensor_dim: 88

# reward
reward_type: l2
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.01
table_collision_reward_weight: -0.1
# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.2  # body width
max_step: 1000
max_collisions_allowed: 500

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: []  # ignore collisions with these robot links

# sensor spec
output: [task_obs, sensor, auxiliary_sensor, depth]
# output: [task_obs]
# image
# Primesense Carmine 1.09 short-range RGBD sensor
# http://xtionprolive.com/primesense-carmine-1.09
fisheye: false
image_width: 128
image_height: 128
vertical_fov: 90
# depth
depth_low: 0.35
depth_high: 3.0
# scan
# SICK TIM571 scanning range finder
# https://docs.fetchrobotics.com/robot_hardware.html
# n_horizontal_rays is originally 661, sub-sampled 1/3
n_horizontal_rays: 228
n_vertical_beams: 1
laser_linear_range: 5.6
laser_angular_range: 240.0
min_laser_dist: 0.05
laser_link_name: rgbd_laser_link

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visual_marker: sphere
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false